const songs = [
    {
        id: 1,
        title: "Mary Had a Little Lamb",
        notes: [
            { note: "E4", timestamp: 0.0, duration: 0.4 },
            { note: "D4", timestamp: 0.5, duration: 0.4 },
            { note: "C4", timestamp: 1.0, duration: 0.4 },
            { note: "D4", timestamp: 1.5, duration: 0.4 },
            { note: "E4", timestamp: 2.0, duration: 0.4 },
            { note: "E4", timestamp: 2.5, duration: 0.4 },
            { note: "E4", timestamp: 3.0, duration: 0.8 },
            { note: "D4", timestamp: 4.0, duration: 0.4 },
            { note: "D4", timestamp: 4.5, duration: 0.4 },
            { note: "D4", timestamp: 5.0, duration: 0.8 },
            { note: "E4", timestamp: 6.0, duration: 0.4 },
            { note: "G4", timestamp: 6.5, duration: 0.4 },
            { note: "G4", timestamp: 7.0, duration: 0.8 }
        ]
    },
    {
        id: 2,
        title: "Twinkle Twinkle Little Star",
        notes: [
            { note: "C4", timestamp: 0.0, duration: 0.4 },
            { note: "C4", timestamp: 0.5, duration: 0.4 },
            { note: "G4", timestamp: 1.0, duration: 0.4 },
            { note: "G4", timestamp: 1.5, duration: 0.4 },
            { note: "A4", timestamp: 2.0, duration: 0.4 },
            { note: "A4", timestamp: 2.5, duration: 0.4 },
            { note: "G4", timestamp: 3.0, duration: 0.8 },
            { note: "F4", timestamp: 4.0, duration: 0.4 },
            { note: "F4", timestamp: 4.5, duration: 0.4 },
            { note: "E4", timestamp: 5.0, duration: 0.4 },
            { note: "E4", timestamp: 5.5, duration: 0.4 },
            { note: "D4", timestamp: 6.0, duration: 0.4 },
            { note: "D4", timestamp: 6.5, duration: 0.4 },
            { note: "C4", timestamp: 7.0, duration: 0.8 }
        ]
    },
    {
        id: 3,
        title: "Jingle Bells",
        notes: [
            { note: "E4", timestamp: 0.0, duration: 0.4 },
            { note: "E4", timestamp: 0.5, duration: 0.4 },
            { note: "E4", timestamp: 1.0, duration: 0.8 },
            { note: "E4", timestamp: 2.0, duration: 0.4 },
            { note: "E4", timestamp: 2.5, duration: 0.4 },
            { note: "E4", timestamp: 3.0, duration: 0.8 },
            { note: "E4", timestamp: 4.0, duration: 0.4 },
            { note: "G4", timestamp: 4.5, duration: 0.4 },
            { note: "C4", timestamp: 5.5, duration: 0.6 },
            { note: "D4", timestamp: 6.5, duration: 0.4 },
            { note: "E4", timestamp: 7.0, duration: 1.0 }
        ]
    },
    {
        id: 4,
        title: "Happy Birthday",
        notes: [
            { note: "C4", timestamp: 0.0, duration: 0.5 },
            { note: "C4", timestamp: 0.6, duration: 0.5 },
            { note: "D4", timestamp: 1.2, duration: 0.5 },
            { note: "C4", timestamp: 1.8, duration: 0.5 },
            { note: "F4", timestamp: 2.4, duration: 0.5 },
            { note: "E4", timestamp: 3.0, duration: 0.8 },

            { note: "C4", timestamp: 4.0, duration: 0.5 },
            { note: "C4", timestamp: 4.6, duration: 0.5 },
            { note: "D4", timestamp: 5.2, duration: 0.5 },
            { note: "C4", timestamp: 5.8, duration: 0.5 },
            { note: "G4", timestamp: 6.4, duration: 0.5 },
            { note: "F4", timestamp: 7.0, duration: 0.8 },

            { note: "C4", timestamp: 8.0, duration: 0.5 },
            { note: "C4", timestamp: 8.6, duration: 0.5 },
            { note: "C5", timestamp: 9.2, duration: 0.5 },
            { note: "A4", timestamp: 9.8, duration: 0.5 },
            { note: "F4", timestamp: 10.4, duration: 0.5 },
            { note: "E4", timestamp: 11.0, duration: 0.5 },
            { note: "D4", timestamp: 11.6, duration: 0.8 },

            { note: "Bb4", timestamp: 12.6, duration: 0.5 },
            { note: "Bb4", timestamp: 13.2, duration: 0.5 },
            { note: "A4", timestamp: 13.8, duration: 0.5 },
            { note: "F4", timestamp: 14.4, duration: 0.5 },
            { note: "G4", timestamp: 15.0, duration: 0.5 },
            { note: "F4", timestamp: 15.6, duration: 1.0 }
        ]
    },
    {
        id: 5,
        title: "Old MacDonald Had a Farm",
        notes: [
            { note: "G4", timestamp: 0.0, duration: 0.4 },
            { note: "G4", timestamp: 0.5, duration: 0.4 },
            { note: "G4", timestamp: 1.0, duration: 0.4 },
            { note: "D4", timestamp: 1.5, duration: 0.4 },
            { note: "E4", timestamp: 2.0, duration: 0.4 },
            { note: "E4", timestamp: 2.5, duration: 0.4 },
            { note: "D4", timestamp: 3.0, duration: 0.8 },

            { note: "B4", timestamp: 4.0, duration: 0.4 },
            { note: "B4", timestamp: 4.5, duration: 0.4 },
            { note: "A4", timestamp: 5.0, duration: 0.4 },
            { note: "A4", timestamp: 5.5, duration: 0.4 },
            { note: "G4", timestamp: 6.0, duration: 0.8 },

            { note: "D4", timestamp: 7.0, duration: 0.4 },
            { note: "G4", timestamp: 7.5, duration: 0.4 },
            { note: "G4", timestamp: 8.0, duration: 0.4 },
            { note: "G4", timestamp: 8.5, duration: 0.4 },
            { note: "D4", timestamp: 9.0, duration: 0.4 },
            { note: "E4", timestamp: 9.5, duration: 0.4 },
            { note: "E4", timestamp: 10.0, duration: 0.4 },
            { note: "D4", timestamp: 10.5, duration: 0.8 }
        ]
    },
    {
        id: 6,
        title: "Beethoven – Ode to Joy",
        notes: [
            { note: "E4", timestamp: 0.0, duration: 0.4 },
            { note: "E4", timestamp: 0.5, duration: 0.4 },
            { note: "F4", timestamp: 1.0, duration: 0.4 },
            { note: "G4", timestamp: 1.5, duration: 0.4 },
            { note: "G4", timestamp: 2.0, duration: 0.4 },
            { note: "F4", timestamp: 2.5, duration: 0.4 },
            { note: "E4", timestamp: 3.0, duration: 0.4 },
            { note: "D4", timestamp: 3.5, duration: 0.4 },
            { note: "C4", timestamp: 4.0, duration: 0.4 },
            { note: "C4", timestamp: 4.5, duration: 0.4 },
            { note: "D4", timestamp: 5.0, duration: 0.4 },
            { note: "E4", timestamp: 5.5, duration: 0.4 },
            { note: "E4", timestamp: 6.0, duration: 0.6 },
            { note: "D4", timestamp: 6.5, duration: 0.3 },
            { note: "D4", timestamp: 7.0, duration: 0.8 }
        ]
    },
    {
        id: 7,
        title: "Mozart – Eine kleine Nachtmusik (simplified)",
        notes: [
            { note: "G4", timestamp: 0.0, duration: 0.5 },
            { note: "D4", timestamp: 0.6, duration: 0.5 },
            { note: "G4", timestamp: 1.2, duration: 0.5 },
            { note: "D4", timestamp: 1.8, duration: 0.5 },
            { note: "G4", timestamp: 2.4, duration: 0.5 },
            { note: "D4", timestamp: 3.0, duration: 0.5 },
            { note: "G4", timestamp: 3.6, duration: 0.5 },
            { note: "B4", timestamp: 4.2, duration: 0.5 },
            { note: "C5", timestamp: 4.8, duration: 0.5 },
            { note: "B4", timestamp: 5.4, duration: 0.5 },
            { note: "G4", timestamp: 6.0, duration: 0.5 },
            { note: "D4", timestamp: 6.6, duration: 0.5 },
            { note: "E4", timestamp: 7.2, duration: 0.5 },
            { note: "F#4", timestamp: 7.8, duration: 0.5 },
            { note: "G4", timestamp: 8.4, duration: 0.8 }
        ]
    },
    {
        id: 8,
        title: "Bach – Minuet in G (simplified)",
        notes: [
            { note: "G4", timestamp: 0.0, duration: 0.45 },
            { note: "A4", timestamp: 0.5, duration: 0.45 },
            { note: "B4", timestamp: 1.0, duration: 0.55 },
            { note: "D4", timestamp: 1.6, duration: 0.55 },
            { note: "G4", timestamp: 2.2, duration: 0.55 },
            { note: "F#4", timestamp: 2.8, duration: 0.55 },
            { note: "E4", timestamp: 3.4, duration: 0.55 },
            { note: "D4", timestamp: 4.0, duration: 0.8 },

            { note: "E4", timestamp: 5.0, duration: 0.55 },
            { note: "C4", timestamp: 5.6, duration: 0.55 },
            { note: "E4", timestamp: 6.2, duration: 0.55 },
            { note: "G4", timestamp: 6.8, duration: 0.55 },
            { note: "F#4", timestamp: 7.4, duration: 0.55 },
            { note: "D4", timestamp: 8.0, duration: 0.8 }
        ]
    },
    {
        id: 9,
        title: "Chopin - Nocturne Op. 9 No. 2 (Intro)",
        notes: [
            { note: "Bb2", timestamp: 0.0, duration: 1.0 },
            { note: "F3", timestamp: 0.0, duration: 1.0 },
            { note: "D4", timestamp: 0.0, duration: 1.0 },
            { note: "Bb4", timestamp: 1.0, duration: 0.4 },
            { note: "C5", timestamp: 1.5, duration: 0.4 },
            { note: "D5", timestamp: 2.0, duration: 0.45 },
            { note: "A4", timestamp: 2.5, duration: 0.45 },
            { note: "Bb4", timestamp: 3.0, duration: 0.45 },
            { note: "G4", timestamp: 3.5, duration: 0.45 },
            { note: "C3", timestamp: 4.0, duration: 1.0 },
            { note: "E3", timestamp: 4.0, duration: 1.0 },
            { note: "G3", timestamp: 4.0, duration: 1.0 },
            { note: "F4", timestamp: 5.0, duration: 0.4 },
            { note: "G4", timestamp: 5.5, duration: 0.4 },
            { note: "A4", timestamp: 6.0, duration: 0.45 },
            { note: "F4", timestamp: 6.5, duration: 0.45 },
            { note: "D4", timestamp: 7.0, duration: 0.8 },
            { note: "D3", timestamp: 8.0, duration: 1.0 },
            { note: "F3", timestamp: 8.0, duration: 1.0 },
            { note: "A3", timestamp: 8.0, duration: 1.0 },
            { note: "F4", timestamp: 9.0, duration: 0.2 },
            { note: "G4", timestamp: 9.25, duration: 0.2 },
            { note: "A4", timestamp: 9.5, duration: 0.2 },
            { note: "Bb4", timestamp: 9.75, duration: 0.2 },
            { note: "C5", timestamp: 10.0, duration: 0.2 },
            { note: "D5", timestamp: 10.25, duration: 0.2 },
            { note: "Eb5", timestamp: 10.5, duration: 0.45 },
            { note: "F5", timestamp: 11.0, duration: 0.45 },
            { note: "D5", timestamp: 11.5, duration: 0.45 },
            { note: "Bb4", timestamp: 12.0, duration: 0.9 }
        ]
    },
    {
        id: 10,
        title: "Debussy - Clair de Lune (Opening)",
        notes: [
            { note: "F#4", timestamp: 0.0, duration: 0.9 },
            { note: "G4", timestamp: 1.0, duration: 0.9 },
            { note: "Bb4", timestamp: 2.0, duration: 0.9 },
            { note: "C#5", timestamp: 3.0, duration: 0.9 },
            { note: "D5", timestamp: 4.0, duration: 0.95 },
            { note: "Bb4", timestamp: 5.0, duration: 0.95 },
            { note: "C#5", timestamp: 6.0, duration: 0.95 },
            { note: "F#4", timestamp: 7.0, duration: 0.9 },
            { note: "G4", timestamp: 8.0, duration: 0.9 },
            { note: "Bb4", timestamp: 9.0, duration: 0.9 },
            { note: "C#5", timestamp: 10.0, duration: 0.9 },
            { note: "D5", timestamp: 11.0, duration: 1.0 },
            { note: "Bb4", timestamp: 12.0, duration: 1.0 },
            { note: "G4", timestamp: 13.0, duration: 0.95 },
            { note: "D3", timestamp: 13.0, duration: 2.0 },
            { note: "G3", timestamp: 13.0, duration: 2.0 },
            { note: "Bb3", timestamp: 13.0, duration: 2.0 },
            { note: "A4", timestamp: 14.0, duration: 0.95 },
            { note: "B4", timestamp: 15.0, duration: 0.95 },
            { note: "C5", timestamp: 16.0, duration: 0.95 },
            { note: "D5", timestamp: 17.0, duration: 0.95 },
            { note: "C5", timestamp: 18.0, duration: 0.95 },
            { note: "B4", timestamp: 19.0, duration: 0.95 },
            { note: "C5", timestamp: 20.0, duration: 0.9 },
            { note: "G3", timestamp: 20.0, duration: 2.0 },
            { note: "C4", timestamp: 20.0, duration: 2.0 },
            { note: "E4", timestamp: 20.0, duration: 2.0 },
            { note: "D5", timestamp: 21.0, duration: 0.9 },
            { note: "E5", timestamp: 22.0, duration: 0.9 },
            { note: "F5", timestamp: 23.0, duration: 0.9 },
            { note: "G5", timestamp: 24.0, duration: 1.2 }
        ]
    },
    {
        id: 11,
        title: "Beethoven - Moonlight Sonata (1st Mvmt)",
        notes: [
            { note: "C#3", timestamp: 0.0, duration: 0.6 },
            { note: "G#3", timestamp: 0.2, duration: 0.6 },
            { note: "C#4", timestamp: 0.4, duration: 0.6 },
            { note: "E4", timestamp: 0.6, duration: 0.6 },
            { note: "G#3", timestamp: 0.8, duration: 0.6 },
            { note: "C#4", timestamp: 1.0, duration: 0.6 },
            { note: "C#3", timestamp: 1.2, duration: 0.6 },
            { note: "G#3", timestamp: 1.4, duration: 0.6 },
            { note: "C#4", timestamp: 1.6, duration: 0.6 },
            { note: "E4", timestamp: 1.8, duration: 0.6 },
            { note: "G#3", timestamp: 2.0, duration: 0.6 },
            { note: "C#4", timestamp: 2.2, duration: 0.6 },
            { note: "G#4", timestamp: 2.4, duration: 0.8 },
            { note: "B3", timestamp: 2.4, duration: 0.6 },
            { note: "G#3", timestamp: 2.6, duration: 0.6 },
            { note: "B3", timestamp: 2.8, duration: 0.6 },
            { note: "F#4", timestamp: 3.0, duration: 0.8 },
            { note: "B3", timestamp: 3.2, duration: 0.6 },
            { note: "G#3", timestamp: 3.4, duration: 0.6 },
            { note: "B3", timestamp: 3.6, duration: 0.6 },
            { note: "E4", timestamp: 3.8, duration: 0.8 },
            { note: "A3", timestamp: 3.8, duration: 0.6 },
            { note: "F#3", timestamp: 4.0, duration: 0.6 },
            { note: "A3", timestamp: 4.2, duration: 0.6 },
            { note: "D#4", timestamp: 4.4, duration: 0.8 },
            { note: "A3", timestamp: 4.6, duration: 0.6 },
            { note: "F#3", timestamp: 4.8, duration: 0.6 },
            { note: "A3", timestamp: 5.0, duration: 0.6 },
            { note: "E4", timestamp: 5.2, duration: 0.8 },
            { note: "G#3", timestamp: 5.2, duration: 0.6 },
            { note: "E3", timestamp: 5.4, duration: 0.6 },
            { note: "G#3", timestamp: 5.6, duration: 0.6 },
            { note: "C#4", timestamp: 5.8, duration: 0.8 },
            { note: "G#3", timestamp: 6.0, duration: 0.6 },
            { note: "E3", timestamp: 6.2, duration: 0.6 },
            { note: "G#3", timestamp: 6.4, duration: 0.6 }
        ]
    },
    {
        id: 12,
        title: "Rachmaninoff - Prelude in C# Minor (Opening)",
        notes: [
            { note: "C#2", timestamp: 0.0, duration: 1.4 },
            { note: "C#3", timestamp: 0.0, duration: 1.4 },
            { note: "G#3", timestamp: 0.0, duration: 1.4 },
            { note: "C#4", timestamp: 0.0, duration: 1.4 },
            { note: "G#4", timestamp: 0.0, duration: 1.4 },
            { note: "C#5", timestamp: 0.0, duration: 1.4 },
            { note: "C#2", timestamp: 1.5, duration: 1.4 },
            { note: "C#3", timestamp: 1.5, duration: 1.4 },
            { note: "G#3", timestamp: 1.5, duration: 1.4 },
            { note: "C#4", timestamp: 1.5, duration: 1.4 },
            { note: "G#4", timestamp: 1.5, duration: 1.4 },
            { note: "C#5", timestamp: 1.5, duration: 1.4 },
            { note: "D#2", timestamp: 3.0, duration: 1.4 },
            { note: "A2", timestamp: 3.0, duration: 1.4 },
            { note: "D#3", timestamp: 3.0, duration: 1.4 },
            { note: "F#3", timestamp: 3.0, duration: 1.4 },
            { note: "A3", timestamp: 3.0, duration: 1.4 },
            { note: "D#4", timestamp: 3.0, duration: 1.4 },
            { note: "C#4", timestamp: 4.5, duration: 0.9 },
            { note: "G#3", timestamp: 4.5, duration: 0.9 },
            { note: "E3", timestamp: 4.5, duration: 0.9 },
            { note: "A2", timestamp: 4.5, duration: 0.9 },
            { note: "B3", timestamp: 5.5, duration: 0.9 },
            { note: "G#3", timestamp: 5.5, duration: 0.9 },
            { note: "D#3", timestamp: 5.5, duration: 0.9 },
            { note: "G#2", timestamp: 5.5, duration: 0.9 },
            { note: "A3", timestamp: 6.5, duration: 0.9 },
            { note: "E3", timestamp: 6.5, duration: 0.9 },
            { note: "C#3", timestamp: 6.5, duration: 0.9 },
            { note: "F#2", timestamp: 6.5, duration: 0.9 },
            { note: "G#3", timestamp: 7.5, duration: 1.0 },
            { note: "E3", timestamp: 7.5, duration: 1.0 },
            { note: "B2", timestamp: 7.5, duration: 1.0 },
            { note: "E2", timestamp: 7.5, duration: 1.0 }
        ]
    },
    {
        id: 13,
        title: "Bach - Prelude in C Major (BWV 846)",
        notes: [
            { note: "C4", timestamp: 0.0, duration: 0.25 },
            { note: "E4", timestamp: 0.2, duration: 0.25 },
            { note: "G4", timestamp: 0.4, duration: 0.25 },
            { note: "C5", timestamp: 0.6, duration: 0.25 },
            { note: "E4", timestamp: 0.8, duration: 0.25 },
            { note: "G4", timestamp: 1.0, duration: 0.25 },
            { note: "C4", timestamp: 1.2, duration: 0.25 },
            { note: "E4", timestamp: 1.4, duration: 0.25 },
            { note: "G4", timestamp: 1.6, duration: 0.25 },
            { note: "C5", timestamp: 1.8, duration: 0.25 },
            { note: "E4", timestamp: 2.0, duration: 0.25 },
            { note: "G4", timestamp: 2.2, duration: 0.25 },
            { note: "B3", timestamp: 2.4, duration: 0.25 },
            { note: "D4", timestamp: 2.6, duration: 0.25 },
            { note: "G4", timestamp: 2.8, duration: 0.25 },
            { note: "D5", timestamp: 3.0, duration: 0.25 },
            { note: "D4", timestamp: 3.2, duration: 0.25 },
            { note: "G4", timestamp: 3.4, duration: 0.25 },
            { note: "B3", timestamp: 3.6, duration: 0.25 },
            { note: "D4", timestamp: 3.8, duration: 0.25 },
            { note: "G4", timestamp: 4.0, duration: 0.25 },
            { note: "D5", timestamp: 4.2, duration: 0.25 },
            { note: "D4", timestamp: 4.4, duration: 0.25 },
            { note: "G4", timestamp: 4.6, duration: 0.25 },
            { note: "A3", timestamp: 4.8, duration: 0.25 },
            { note: "D4", timestamp: 5.0, duration: 0.25 },
            { note: "F#4", timestamp: 5.2, duration: 0.25 },
            { note: "C5", timestamp: 5.4, duration: 0.25 },
            { note: "D4", timestamp: 5.6, duration: 0.25 },
            { note: "F#4", timestamp: 5.8, duration: 0.25 },
            { note: "A3", timestamp: 6.0, duration: 0.25 },
            { note: "D4", timestamp: 6.2, duration: 0.25 },
            { note: "F#4", timestamp: 6.4, duration: 0.25 },
            { note: "C5", timestamp: 6.6, duration: 0.25 },
            { note: "D4", timestamp: 6.8, duration: 0.25 },
            { note: "F#4", timestamp: 7.0, duration: 0.3 }
        ]
    },
    {
        id: 14,
        title: "Für Elise - Beethoven (Main Theme)",
        notes: [
            { note: "E5", timestamp: 0.0, duration: 0.4 },
            { note: "D#5", timestamp: 0.5, duration: 0.4 },
            { note: "E5", timestamp: 1.0, duration: 0.4 },
            { note: "D#5", timestamp: 1.5, duration: 0.4 },
            { note: "E5", timestamp: 2.0, duration: 0.4 },
            { note: "B4", timestamp: 2.5, duration: 0.4 },
            { note: "D5", timestamp: 3.0, duration: 0.4 },
            { note: "C5", timestamp: 3.5, duration: 0.45 },
            { note: "A4", timestamp: 4.0, duration: 0.8 },
            { note: "A2", timestamp: 4.0, duration: 1.0 },
            { note: "E3", timestamp: 4.0, duration: 1.0 },
            { note: "A3", timestamp: 4.0, duration: 1.0 },
            { note: "C4", timestamp: 5.0, duration: 0.4 },
            { note: "E4", timestamp: 5.5, duration: 0.4 },
            { note: "A4", timestamp: 6.0, duration: 0.4 },
            { note: "B4", timestamp: 6.5, duration: 0.45 },
            { note: "E2", timestamp: 7.0, duration: 1.0 },
            { note: "E3", timestamp: 7.0, duration: 1.0 },
            { note: "G#3", timestamp: 7.0, duration: 1.0 },
            { note: "C5", timestamp: 7.5, duration: 0.45 },
            { note: "E4", timestamp: 8.0, duration: 0.4 },
            { note: "G#4", timestamp: 8.5, duration: 0.4 },
            { note: "B4", timestamp: 9.0, duration: 0.45 },
            { note: "A2", timestamp: 9.5, duration: 1.0 },
            { note: "E3", timestamp: 9.5, duration: 1.0 },
            { note: "A3", timestamp: 9.5, duration: 1.0 },
            { note: "E5", timestamp: 10.0, duration: 0.4 },
            { note: "D#5", timestamp: 10.5, duration: 0.4 },
            { note: "E5", timestamp: 11.0, duration: 0.4 },
            { note: "D#5", timestamp: 11.5, duration: 0.4 },
            { note: "E5", timestamp: 12.0, duration: 0.4 },
            { note: "B4", timestamp: 12.5, duration: 0.4 },
            { note: "D5", timestamp: 13.0, duration: 0.4 },
            { note: "C5", timestamp: 13.5, duration: 0.45 },
            { note: "A4", timestamp: 14.0, duration: 0.9 }
        ]
    },
    {
        id: 15,
        title: "Queen - Bohemian Rhapsody (Intro)",
        notes: [
            { note: "Bb4", timestamp: 0.0, duration: 0.45 },
            { note: "G4", timestamp: 0.5, duration: 0.45 },
            { note: "D4", timestamp: 1.0, duration: 0.45 },
            { note: "Bb4", timestamp: 1.5, duration: 0.45 },
            { note: "C5", timestamp: 2.0, duration: 0.45 },
            { note: "G4", timestamp: 2.5, duration: 0.45 },
            { note: "G3", timestamp: 3.0, duration: 0.7 },
            { note: "G4", timestamp: 3.2, duration: 0.55 },
            { note: "Bb4", timestamp: 3.8, duration: 0.55 },
            { note: "C5", timestamp: 4.4, duration: 0.55 },
            { note: "Bb4", timestamp: 5.0, duration: 0.55 },
            { note: "G4", timestamp: 5.6, duration: 0.4 },
            { note: "Bb3", timestamp: 6.0, duration: 0.7 },
            { note: "F4", timestamp: 6.2, duration: 0.5 },
            { note: "G4", timestamp: 6.8, duration: 0.5 },
            { note: "G#4", timestamp: 7.4, duration: 0.5 },
            { note: "G4", timestamp: 8.0, duration: 0.5 },
            { note: "F4", timestamp: 8.6, duration: 0.4 },
            { note: "Eb3", timestamp: 9.0, duration: 0.7 },
            { note: "Eb4", timestamp: 9.2, duration: 0.55 },
            { note: "F4", timestamp: 9.8, duration: 0.55 },
            { note: "Eb4", timestamp: 10.4, duration: 0.55 },
            { note: "D4", timestamp: 11.0, duration: 0.55 },
            { note: "C4", timestamp: 11.6, duration: 0.4 },
            { note: "C3", timestamp: 12.0, duration: 0.7 },
            { note: "C4", timestamp: 12.2, duration: 0.5 },
            { note: "D4", timestamp: 12.8, duration: 0.5 },
            { note: "Eb4", timestamp: 13.4, duration: 0.55 },
            { note: "D4", timestamp: 14.0, duration: 0.3 },
            { note: "C4", timestamp: 14.3, duration: 0.3 },
            { note: "Bb3", timestamp: 14.6, duration: 0.4 },
            { note: "G3", timestamp: 15.0, duration: 0.8 }
        ]
    },
    {
        id: 16,
        title: "Heart and Soul",
        notes: [
            { note: "C4", timestamp: 0.0, duration: 0.5 },
            { note: "A4", timestamp: 0.6, duration: 0.5 },
            { note: "F4", timestamp: 1.2, duration: 0.5 },
            { note: "G4", timestamp: 1.8, duration: 0.5 },
    
            { note: "C5", timestamp: 2.4, duration: 0.5 },
            { note: "A4", timestamp: 3.0, duration: 0.5 },
            { note: "F4", timestamp: 3.6, duration: 0.5 },
            { note: "G4", timestamp: 4.2, duration: 0.5 },
    
            { note: "C4", timestamp: 4.8, duration: 0.5 },
            { note: "A4", timestamp: 5.4, duration: 0.5 },
            { note: "F4", timestamp: 6.0, duration: 0.5 },
            { note: "G4", timestamp: 6.6, duration: 0.5 },
    
            { note: "E4", timestamp: 7.2, duration: 0.5 },
            { note: "G4", timestamp: 7.8, duration: 0.5 },
            { note: "C5", timestamp: 8.4, duration: 0.5 },
            { note: "B4", timestamp: 9.0, duration: 0.8 }
        ]
    }
    
];

// Check if songs already exist in local storage before setting the default ones
const savedSongs = localStorage.getItem('pianoSongs');
if (savedSongs) {
    try {
        window.PIANO_SONGS = JSON.parse(savedSongs);
    } catch (e) {
        window.PIANO_SONGS = songs;
    }
} else {
    window.PIANO_SONGS = songs;
}
